### PR TITLE
Setup pool connection to postgres db

### PR DESCRIPTION
**Pull request by tlrhlt**
1. setup and export query functionality to db
2. installed node-postgres for pool connectivity

### CODE REVIEW

**Review by jespin457 — APPROVED** [review]
Looks all good to me!

**Review by avatarwnd — APPROVED** [review]
looks fine to me.

**Review by avatarwnd — APPROVED** [review]
looks good to me.

**Review by jespin457 — APPROVED** [review]
Reviewed each file--looks good to me!

**Pull request merged**
